language: objective-c
before_install:
  - gem install xcpretty -N
  - gem install cocoapods --pre --quiet
  - gem install slather
  - pod setup --silent
  - pod repo update --silent
script:
  - pod lib lint Bolts.podspec
  - pod lib lint --use-libraries Bolts.podspec
  - set -o pipefail
  - xcodebuild -project Bolts.xcodeproj -sdk iphonesimulator -scheme Bolts test | xcpretty -c
  - xcodebuild -project Bolts.xcodeproj -sdk macosx -scheme MacBolts test | xcpretty -c
after_success:
  - slather
