language: objective-c
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail && xcodebuild -project Bolts.xcodeproj -sdk iphonesimulator -scheme Bolts -configuration Debug test | xcpretty -c
  - set -o pipefail && xcodebuild -project Bolts.xcodeproj -sdk macosx -scheme MacBolts test | xcpretty -c ; exit